chore: Adjust ci build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,63 +1,85 @@
-name: CI
+name: Build
 
-on: [push]
+on:
+    push:
+        branches:
+            - main
+            - develop
+    pull_request:
+    merge_group:
 
 permissions:
-  security-events: write
-  contents: read
-  actions: read
+    # This is required for requesting the JWT
+    id-token: write
+    security-events: write
+    contents: read
+    # This is required for actions/checkout
+    actions: read
+    issues: write
+    # For reporting
+    attestations: write
+    checks: write
+    # For Junit Reporting commenting
+    pull-requests: write
 
 jobs:
-  build:
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-        java: [21, 25]
-      fail-fast: false
+    build:
+        strategy:
+            matrix:
+                os: [ ubuntu-latest ]
+                java: [ 21, 25 ]
+            fail-fast: false
 
-    runs-on: ${{ matrix.os }}
+        runs-on: ${{ matrix.os }}
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+        steps:
+            -   name: Checkout
+                uses: actions/checkout@v3
 
-      - name: Set up cache for ~./m2/repository
-        uses: actions/cache@v3
-        with:
-          path: ~/.m2/repository
-          key: maven-${{ matrix.os }}-java${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            maven-${{ matrix.os }}-java${{ matrix.java }}-
-            maven-${{ matrix.os }}-
-      - name: Set up JDK
-        uses: actions/setup-java@v3
-        with:
-          java-version: ${{ matrix.java }}
-          distribution: 'adopt'
+            -   name: Set up cache for ~./m2/repository
+                uses: actions/cache@v3
+                with:
+                    path: ~/.m2/repository
+                    key: maven-${{ matrix.os }}-java${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('.mvn/wrapper/maven-wrapper.properties') }}
+                    restore-keys: |
+                        maven-${{ matrix.os }}-java${{ matrix.java }}-
+                        maven-${{ matrix.os }}-
 
-  security-scan:
-    uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v2
-    with:
-      java-cache: 'maven'
-      java-version: 21
+            -   name: Set up JDK
+                uses: actions/setup-java@v3
+                with:
+                    java-version: ${{ matrix.java }}
+                    distribution: "adopt"
 
-  deploy:
-    needs: [build]
-    runs-on: ubuntu-latest
+            -   name: Build with Maven
+                run: ./mvnw --batch-mode clean install
 
-    steps:
-      - name: Check out
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Set up JDK 21
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'adopt'
-          java-version: 21
+            -   name: Publish Test Report
+                uses: mikepenz/action-junit-report@v5
+                if: success() || failure() # always run even if the previous step fails
+                with:
+                    report_paths: '**/target/*/TEST-*.xml'
 
-      - name: publish release package
-        if: contains( github.ref, 'main' ) || contains( github.base_ref, 'main' )
-        env:
-          JENKINS_MAVEN_PASS: ${{ secrets.JENKINS_MAVEN_PASS }}
-        run: ./mvnw -s .github/workflows/m2.settings.xml deploy -DskipTests=true
+# TODO: Enable PMD
+#            -   name: Run PMD checks
+#                run: ./mvnw pmd:check
+
+    build-results:
+        name: Build results
+        if: ${{ always() }}
+        runs-on: ubuntu-latest
+        needs:
+            - build
+        steps:
+            -   name: Check out
+                uses: actions/checkout@v3
+                with:
+                    fetch-depth: 0
+            -   run: exit 1
+                # see https://stackoverflow.com/a/67532120/4907315
+                if: >-
+                    ${{
+                          contains(needs.*.result, 'failure')
+                      || contains(needs.*.result, 'cancelled')
+                          || contains(needs.*.result, 'skipped')
+                          }}
